const actionEnum = Object.freeze({
    "APPLICATION_USER_LOGIN": "APPLICATION_USER_LOGIN",
    "APPLICATION_USER_LOGOUT": "APPLICATION_USER_LOGOUT",
    "LOGIN_PAGE_REQUEST_STATUS_CHANGED": "LOGIN_PAGE_REQUEST_STATUS_CHANGED",
    "REGISTER_PAGE_REQUEST_STATUS_CHANGED": "REGISTER_PAGE_REQUEST_STATUS_CHANGED",
    "MAIN_PAGE_REQUEST_STATUS_CHANGED": "MAIN_PAGE_REQUEST_STATUS_CHANGED",
    "MAIN_PAGE_CAR_LIST_CHANGED": "MAIN_PAGE_CAR_LIST_CHANGED"
});

export default actionEnum;